### ISSUE TITLE
Object-fit

### ISSUE THREAD

**Issue by OluwatobilobaIbuola** [Olixc/axon-redactr#20]
In main__right div, Kindly nest the image tag into a div. Then style the image to contain/fill the div. Use object-fit. If you notice, there is a break at a certain viewport that causes overflow x-axis. Unless we intend to change the style of the section, then apply overflow-x:auto @Olixpin

**Comment by Olixc** [comment]
Noted. I discovered that too. Will be fixed

**Comment by Olixc** [comment]
Fixed
