### ISSUE TITLE
Resolve lines

### ISSUE THREAD

**Issue by OluwatobilobaIbuola** [Olixc/axon-redactr#26]
Check the none-html and none-css markdown to copy lines of code to be used as appropriate. check the update and let me know how well it suit the design. @Olixc

**Comment by Olixc** [comment]
Please can you explain better what you mean. I don't get it boss.

**Comment by Olixc** [comment]
I think you should work on it pop up. 
let me focus on the other sections needed for the hoempage. I need to help the team members. Most are having challenges using git

**Comment by OluwatobilobaIbuola** [comment]
Its okay. I will fix it.
